version: '3.8'

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"  # 80번 포트를 host와 container 맵핑
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf  # nginx 설정 파일 volume 맵핑
    restart: 'unless-stopped'  # 내부에서 에러로 인해 container가 죽을 경우 restart
  
  backend-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-server
    expose:
      - "3000"  # 다른 컨테이너에게 3000번 포트 오픈
    volumes:
      - ./env/.env:/deploy-app/env/.env
      - ./src:/deploy-app/src
    restart: "unless-stopped"